name: Linting and tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:36

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        dnf -y update fedora-gpg-keys
        dnf -y install python3 python3-gobject python3-pip gtk4-devel gtk4 \
                       libadwaita libadwaita-devel glib2-devel \
                       meson xorg-x11-server-Xvfb mesa-dri-drivers
        pip install flake8 flake8-tabs pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        adduser builder
        chown -R builder .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82,F821 --show-source --statistics --use-flake8-tabs
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --statistics --use-flake8-tabs
    - name: Run tests
      run: sudo -Hu builder ./run-tests
