name: Linting and tests

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - 'README.md'
      - 'CODINGSTYLE.md'
      - 'LICENSE'
      - 'po/**'
      - 'docs/**'
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - 'README.md'
      - 'CODINGSTYLE.md'
      - 'LICENSE'
      - 'po/**'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:sid

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt update -y
        apt install -y libgtk-4-1 libadwaita-1-0 python3 python3-pip \
                       python3-gi xvfb meson libglib2.0-bin libglib2.0-dev \
                       libgl1-mesa-dri gir1.2-gtk-4.0 gir1.2-adw-1 \
                       dbus dbus-x11 flake8 python3-pytest python3-coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82,F821 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --statistics
    - name: Run tests
      run: ./run-tests
